### ISSUE TITLE
event are returning empty for recent jobs in Argus

### ISSUE THREAD

**Issue by fruch** [scylladb/argus#253] opened 2023-06-04 11:32 UTC
https://argus.scylladb.com/test/6e39841d-5ed5-4f83-aa70-f51949559234/runs?additionalRuns[]=0b6cacb3-426c-48a1-b9c4-2121bcd65486

https://argus.scylladb.com/api/v1/run/scylla-cluster-tests/0b6cacb3-426c-48a1-b9c4-2121bcd65486

```
        "config_files": [
            "test-cases/longevity/longevity-10gb-3h.yaml"
        ],
        "end_time": "2023-06-04 11:06:58 UTC",
        "events": [],
        "group_id": "31925ecd-2273-4ff7-9012-4d31fe61eef5",
        "heartbeat": 1685876817,
        "id": "0b6cacb3-426c-48a1-b9c4-2121bcd65486",
        "investigation_status": "not_investigated",
```

**Comment by k0machi** [comment] 2023-06-05 16:04
Going to close this for now as this issue seems to have the same root cause as #252, instance running out of disk space. I've re-ran the longevity in question and it submitted the events, if this issue repeats I'll reopen.

**Closed by k0machi** 2023-06-05 16:04 UTC
